apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vgj88oxia-python
  janus-idp.io/tekton: vgj88oxia-python
  backstage.io/kubernetes-id: vgj88oxia-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vgj88oxia-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
