apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: vgj88oxia-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vgj88oxia-python 
  name: vgj88oxia-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vgj88oxia-python
    weight: 100 
